substitutions:
  name: linky-bridge
  timezone: "Europe/Paris"

  # UART TIC
  uart_tic_tx_pin: GPIO17
  uart_tic_rx_pin: GPIO16

  # UART RS485
  uart_rs485_tx_pin: GPIO13
  uart_rs485_rx_pin: GPIO21
  uart_rs485_baud_rate: 9600
  uart_rs485_stop_bits: 1
  uart_rs485_parity: NONE

  # UART RS485 secondaire (optionnel)
  uart_rs485_2_tx_pin: GPIO38
  uart_rs485_2_rx_pin: GPIO40
  uart_rs485_2_baud_rate: 9600
  uart_rs485_2_stop_bits: 1
  uart_rs485_2_parity: NONE

  #Modbus
  modbus_address: 1
  modbus_flow_control_pin: GPIO14

  #Modbus2 (optionnel)
  modbus2_address: 1
  modbus2_flow_control_pin: GPIO39

esphome:
  name: ${name}
  friendly_name: ${name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:
  level: NONE
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  ap:
    ssid: "fallback_ap"
    password: "fallback_password"

api:

ota:
  - platform: esphome
    password: !secret ota_pass

web_server:
  port: 80

mdns:
  disabled: false

time:
  - platform: sntp
    timezone: ${timezone}
    id: my_time

uart:
  - id: uart_rs485
    baud_rate: ${uart_rs485_baud_rate}
    tx_pin: ${uart_rs485_tx_pin}
    rx_pin: ${uart_rs485_rx_pin}
    stop_bits: ${uart_rs485_stop_bits}
    parity: ${uart_rs485_parity}

  - id: uart_tic
    baud_rate: 9600
    tx_pin: ${uart_tic_tx_pin}
    rx_pin: ${uart_tic_rx_pin}
    parity: EVEN
    data_bits: 7
    stop_bits: 1

  - id: uart_rs485_2
    baud_rate: ${uart_rs485_2_baud_rate}
    tx_pin: ${uart_rs485_2_tx_pin}
    rx_pin: ${uart_rs485_2_rx_pin}
    stop_bits: ${uart_rs485_2_stop_bits}
    parity: ${uart_rs485_2_parity}

teleinfo:
  id: myteleinfo
  uart_id: uart_tic
  update_interval: 1s
  historical_mode: false

modbus:
  - id: modbus1
    uart_id: uart_rs485
    flow_control_pin: ${modbus_flow_control_pin}
    send_wait_time: 200ms
    role: server

  - id: modbus2
    uart_id: uart_rs485_2
    flow_control_pin: ${modbus2_flow_control_pin}
    send_wait_time: 200ms
    role: server

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass
  discovery: true

espnow:
  auto_add_peer: true

<<: !include modbus_map.yaml
