text_sensor:
  - platform: teleinfo
    tag_name: "NGTF"
    name: "Type de contrat"
    id: ngtf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "LTARF"
    name: "Tarif en cours"
    id: ltarf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "PJOURF+1"
    name: "Profil tarifaire prévu demain"
    id: pjourf_plus1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "PPOINTE"
    name: "Jour de pointe prévu demain"
    id: ppointe
    teleinfo_id: myteleinfo

sensor:
  # Informations TIC
  # Index énergie par contrat
  - platform: teleinfo
    tag_name: "EAST"
    name: "Énergie totale soutirée"
    unit_of_measurement: "Wh"
    id: east
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EAIT"
    name: "Énergie totale injectée"
    unit_of_measurement: "Wh"
    id: eait
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF01"
    name: "Énergie période 1"
    unit_of_measurement: "Wh"
    id: easf01
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF02"
    name: "Énergie période 2"
    unit_of_measurement: "Wh"
    id: easf02
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF03"
    name: "Énergie période 3"
    unit_of_measurement: "Wh"
    id: easf03
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF04"
    name: "Énergie période 4"
    unit_of_measurement: "Wh"
    id: easf04
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF05"
    name: "Énergie période 5"
    unit_of_measurement: "Wh"
    id: easf05
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "EASF06"
    name: "Énergie période 6"
    unit_of_measurement: "Wh"
    id: easf06
    teleinfo_id: myteleinfo

  # Courants par phase
  - platform: teleinfo
    tag_name: "IRMS1"
    name: "Courant phase 1"
    unit_of_measurement: "A"
    id: irms1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "IRMS2"
    name: "Courant phase 2"
    unit_of_measurement: "A"
    id: irms2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "IRMS3"
    name: "Courant phase 3"
    unit_of_measurement: "A"
    id: irms3
    teleinfo_id: myteleinfo

  # Tensions par phase
  - platform: teleinfo
    tag_name: "URMS1"
    name: "Tension phase 1"
    unit_of_measurement: "V"
    id: urms1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "URMS2"
    name: "Tension phase 2"
    unit_of_measurement: "V"
    id: urms2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "URMS3"
    name: "Tension phase 3"
    unit_of_measurement: "V"
    id: urms3
    teleinfo_id: myteleinfo

  # Puissance instantanée
  - platform: teleinfo
    tag_name: "SINSTS"
    name: "Puissance apparente totale"
    unit_of_measurement: "VA"
    id: sinsts
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SINST1"
    name: "Puissance phase 1"
    unit_of_measurement: "VA"
    id: sinst1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SINST2"
    name: "Puissance phase 2"
    unit_of_measurement: "VA"
    id: sinst2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SINST3"
    name: "Puissance phase 3"
    unit_of_measurement: "VA"
    id: sinst3
    teleinfo_id: myteleinfo

  # Puissance max du jour
  - platform: teleinfo
    tag_name: "SMAXSN"
    name: "Puissance max totale"
    unit_of_measurement: "VA"
    id: smaxsn
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SMAXSN1"
    name: "Puissance max phase 1"
    unit_of_measurement: "VA"
    id: smaxsn1
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SMAXSN2"
    name: "Puissance max phase 2"
    unit_of_measurement: "VA"
    id: smaxsn2
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "SMAXSN3"
    name: "Puissance max phase 3"
    unit_of_measurement: "VA"
    id: smaxsn3
    teleinfo_id: myteleinfo

  # Autres
  - platform: teleinfo
    tag_name: "PCOUP"
    name: "Puissance de coupure"
    unit_of_measurement: "VA"
    id: pcoup
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "PREF"
    name: "Puissance de référence"
    unit_of_measurement: "kVA"
    id: pref
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "CCASN"
    name: "Compteur de dépassement"
    id: ccasn
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "NTARF"
    name: "Index tarifaire en cours"
    id: ntarf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "NJOURF"
    name: "Jour tarifaire actuel"
    id: njourf
    teleinfo_id: myteleinfo

  - platform: teleinfo
    tag_name: "NJOURF+1"
    name: "Jour tarifaire prévu demain"
    id: njourf_plus1
    teleinfo_id: myteleinfo

#Registres TIC
modbus_controller:
  - id: modbus_slave
    address: ${modbus_address}
    modbus_id: modbus1
    server_registers:
      # 🔵 BASE
      - address: 0
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(east).state;'
      - address: 2
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(eait).state;'

      # 🔵 HC/HP
      - address: 4
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf01).state;'
      - address: 6
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf02).state;'

      # 🔴 EJP
      - address: 8
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf01).state;'
      - address: 10
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf02).state;'

      # 🔵⚪🔴 TEMPO
      - address: 12
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf01).state;'
      - address: 14
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf02).state;'
      - address: 16
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf03).state;'
      - address: 18
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf04).state;'
      - address: 20
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf05).state;'
      - address: 22
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(easf06).state;'

      # ⚡ Courants
      - address: 24
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(irms1).state;'
      - address: 25
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(irms2).state;'
      - address: 26
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(irms3).state;'

      # 🔌 Tensions
      - address: 27
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(urms1).state;'
      - address: 28
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(urms2).state;'
      - address: 29
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(urms3).state;'

      # ⚡ Puissance instantanée
      - address: 30
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(sinsts).state;'
      - address: 32
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(sinst1).state;'
      - address: 34
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(sinst2).state;'
      - address: 36
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(sinst3).state;'

      # 📈 Puissance max
      - address: 38
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(smaxsn).state;'
      - address: 40
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(smaxsn1).state;'
      - address: 42
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(smaxsn2).state;'
      - address: 44
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(smaxsn3).state;'

      # 🔒 Puissance de coupure / référence
      - address: 46
        value_type: U_DWORD
        read_lambda: 'return (uint32_t)id(pcoup).state;'
      - address: 48
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(pref).state;'

      # 📊 Dépassement
      - address: 49
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(ccasn).state;'

      # 🗓️ Calendrier tarifaire
      - address: 50
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(ntarf).state;'
      - address: 51
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(njourf).state;'
      - address: 52
        value_type: U_WORD
        read_lambda: 'return (uint16_t)id(njourf_plus1).state;'

      # 🟢 Texte : Type de contrat
      - address: 53
        value_type: U_QWORD
        read_lambda: 'return strtoull(id(ngtf).state.c_str(), nullptr, 10);'

      # 🟢 Texte : Tarif en cours
      - address: 57
        value_type: U_QWORD
        read_lambda: 'return strtoull(id(ltarf).state.c_str(), nullptr, 10);'

      # 🟢 Texte : Profil tarifaire prévu demain
      - address: 61
        value_type: U_QWORD
        read_lambda: 'return strtoull(id(pjourf_plus1).state.c_str(), nullptr, 10);'

      # 🟢 Texte : Jour de pointe prévu demain
      - address: 65
        value_type: U_QWORD
        read_lambda: 'return strtoull(id(ppointe).state.c_str(), nullptr, 10);'
