esphome:
  name: linky_bridge

external_components:
  - source: github://tgrauss/linky-bridge/custom_components

uart:
  id: uart_teleinfo
  rx_pin: GPIO16
  baud_rate: 1200
  stop_bits: 1
  parity: EVEN

teleinfo:
  id: linky_tic

modbus:
  id: modbus_bus
  uart_id: uart_teleinfo

modbus_controller:
  id: modbus_slave
  address: 10
  modbus_id: modbus_bus

sensor:
  - platform: teleinfo
    tag_name: "PAPP"
    name: "Linky Puissance Apparente"
    id: papp

  - platform: teleinfo
    tag_name: "IINST"
    name: "Linky Courant Instantané"
    id: iinst

  - platform: teleinfo
    tag_name: "BASE"
    name: "Linky Index BASE"
    id: base

  - platform: modbus_controller
    modbus_controller_id: modbus_slave
    name: "Modbus - PAPP"
    address: 0x0000
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return (uint16_t) id(papp).state;

  - platform: modbus_controller
    modbus_controller_id: modbus_slave
    name: "Modbus - IINST"
    address: 0x0001
    register_type: holding
    value_type: U_WORD
    lambda: |-
      return (uint16_t) id(iinst).state;

  - platform: modbus_controller
    modbus_controller_id: modbus_slave
    name: "Modbus - BASE"
    address: 0x0002
    register_type: holding
    value_type: U_DWORD
    lambda: |-
      return (uint32_t) id(base).state;

custom_component:
  - lambda: |-
      auto bridge = new LinkyBridge();
      bridge->set_papp(id(papp));
      bridge->set_iinst(id(iinst));
      bridge->set_base(id(base));
      return {bridge};
